Query argument static
jongpie/NebulaFramework pull request #39
Opened 2017-05-13 02:38 UTC by jamessimone

Make query argument formatter static

2017-05-28 17:54 UTC, jongpie requested changes

2017-05-28 17:54 UTC, jongpie commented on src/classes/QueryArgumentFormatter.cls
> +    private QueryArgumentFormatter(Object argumentValue) {
I would just change all of the methods to be static methods & completely eliminate the constructor

2017-05-28 17:54 UTC, jongpie commented on src/classes/QueryArgumentFormatter.cls
> +    public static String VALUE(Object argumentValue) {
I'd just scrap this method and make getValue a static method (and eliminate the constructor)

2017-05-31 18:45 UTC, jamessimone commented
I'm gonna close this so we can focus on getting a release out.

2017-05-31 18:45 UTC, closed without merging